//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryView
    {
        public int GuestID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string NumOfGuests { get; set; }
        public string RoomBooked { get; set; }
        public string BookingFrom { get; set; }
        public string BookingTo { get; set; }
        public string BookingDate { get; set; }
        public string CheckedIn { get; set; }
        public string CheckedOut { get; set; }
        public string RoomCost { get; set; }
        public Nullable<int> TotalCharge { get; set; }
    }
}
